
start_menu_dict_en = {
    "Battleships vs CPU": "Battleships vs CPU",
    "Return to settings": "Return to settings",
    "Lets play": "Let's play",
    "Set ships": "Set ships",
    "️Battleships": "Battleships",
    "Change desired settings": "Change desired settings",
    "Auto": "Auto",
    "Set ships again": "Set ships again",
    "Done": "Done",
    "Complete setup": "Complete setup",
    "Start the game": "Start the game",
    "Start": "Start",
    "Are you ready": "Are you ready",
    "Set": "Set",
    "cell ship": "cell ship",
    "Select coordinates to set a ship": "Select coordinates to set a ship",
    "Set this ship": "Set this ship",
    "Horizontal": "Horizontal",
    "Vertical": "Vertical",
    "Set ships and start the game": "Save ships and start the game",
    "Ships on board": "Ships on board",
    "You win, no ships left": "You win, no ships left",
    "Pass turn to CPU": "Pass turn to CPU",
    "Select coordinates to shoot": "Select coordinates to shoot",
    "Shoot": "Shoot",
    "Miss": "Miss",
    "Ship": "Ship",
    "Hit": "Hit",
    "Sunk": "Sunk",
    "Set your ships": "Set your ships",
    "Set difficulty": "Set difficulty",
    "Ships cannot touch each other or overlap the borders": "Ships cannot touch each other or overlap the borders",
    "Continue": "Continue",
    "You Hit": "You Hit",
    "You Miss": "You Miss",
    "Good shot": "Good shot",
    "You have": "You have",
    "ships left to sink": "ships left to sink",
    "You have sunk all ships": "You have sunk all ships",
    "You cannot shoot there": "You cannot shoot there",
    "won the game! With ships left": "won the game! With ships left",
    "and": "and",
    "shots missed of total": "shots missed of total",
    "Loser missed": "Loser missed",
    "of total": "of total",
    "shots. Game over after": "shots. Game over after",
    "turns": "turns",
    "GAME OVER": "GAME OVER",
    "Next turn": "Next turn",
    "Time to shoot": "Time to shoot",
    "You will fight on": "You will fight on",
    "difficulty against CPU": "difficulty against CPU",
    "shoot first": "shoot first",
    "CPU shoot": "CPU shoot",
    "and misses! Your turn": "and misses!\nYour turn",
    "and hit": "and hit",
    "CPU sunk your ship": "CPU sunk your ship",
    "Set your ships: Done": "Set your ships: Done",
    "Easy": "Easy",
    "Hard": "Hard",
    "Medium": "Medium",
    "Manually": "Manually",
    "Automatically": "Automatically",
    "Set turns": "Set turns",
    "You first": "You first",
    "You second": "You second",
    "Print my sea": "Print my sea",
    "Print enemys sea": "Print enemy's sea",
    "shots.Game over after": "shots.Game over after",
}

start_menu_dict_ru = {

    "Battleships vs CPU": "Морской бой vs CPU",
    "Return to settings": "Вернуться к настройкам",
    "Lets play": "Начать игру",
    "Set ships": "Установить корабли",
    "️Battleships": "Морской бой",
    "Change desired settings": "Изменить настройки",
    "Auto": "Авто",
    "Set ships again": "Установить корабли еще раз",
    "Done": "Готово",
    "Complete setup": "Завершить установку",
    "Start the game": "Начать игру",
    "Start": "Начать",
    "Are you ready": "Вы готовы?",
    "Set": "Установить",
    "cell ship": "корабль",
    "Select coordinates to set a ship": "Выберите координаты для установки корабля",
    "Set this ship": "Установить этот корабль",
    "Horizontal": "Горизонтально",
    "Vertical": "Вертикально",
    "Set ships and start the game": "Сохраните корабли и начните игру",
    "Ships on board": "Корабли в море",
    "You win, no ships left": "Вы победили, не осталось кораблей",
    "Pass turn to CPU": "Передать ход CPU",
    "Select coordinates to shoot": "Выберите координаты для выстрела",
    "Shoot": "Выстрел",
    "Miss": "Промах",
    "Ship": "Корабль",
    "Hit": "Попадание",
    "Sunk": "Утопление",
    "Set your ships": "Установите свои корабли",
    "Set difficulty": "Установите сложность",
    "Ships cannot touch each other or overlap the borders": "Корабли не могут касаться друг друга или пересекать границы",
    "Continue": "Продолжать",
    "You Hit": "Попадание",
    "You Miss": "Мимо",
    "Good shot": "Хороший выстрел",
    "You have": "Осталось",
    "ships left to sink": "кораблей утопить",
    "You have sunk all ships": "Вы потопили все корабли",
    "You cannot shoot there": "Туда нельзя стрелять",
    "won the game! With ships left": "выиграл игру! Кораблей остались",
    "and": "и",
    "shots missed of total": "пропущенных выстрелов из",
    "Loser missed": "Проигравший промазал",
    "of total": "из",
    "shots. Game over after": "выстрелов. Игра окончена за",
    "turns": "ходов",
    "GAME OVER": "ИГРА ЗАКОНЧЕНА",
    "Next turn": "Следующий ход",
    "Time to shoot": "Время стрелять",
    "You will fight on": "Вы будете сражаться на",
    "difficulty against CPU": "сложности против CPU",
    "shoot first": "стреляет первым",
    "CPU shoot": "CPU стреляет",
    "and misses! Your turn": "и мимо!\nТвой ход",
    "and hit": "и попадает",
    "CPU sunk your ship": "CPU потопил твой корабль",
    "Set your ships: Done": "Установить свои корабли: Готово",
    "Easy": "лёгкой",
    "Hard": "тяжёлой",
    "Medium": "средней",
    "Set turns": "Выбрать очерёдность",
    "You first": "Xодить первым",
    "You second": "Xодить вторым",
    "Print my sea": "Распечатай мое море",
    "Print enemys sea": "Распечатай море врага",
    "shots.Game over after": "выстрелов.Игра окончена после",
    "Manually" :"Вручную",
    "Automatically" :"Автоматически",
}
